add description of Social Force Model
PedestrianDynamics/PedestrianDynamics.github.io pull request #23
Opened 2024-02-27 14:26 UTC by ChristianHirt

2024-03-19 09:25 UTC, chraibi requested changes

2024-03-19 09:25 UTC, chraibi commented on content/models/social_force_model/index.md
> +There are three basic forces that affect an individual. The driving force represents a person's desire to move in a certain direction, independent of other people and obstacles. The agent force is ca
Remove empty line before this line

The model defines forces that affect an individual:
- A driving force ...
- A repulsive force ...
- and a an obstacle force ...

2024-03-19 09:25 UTC, chraibi commented on content/models/social_force_model/index.md
> +* $v_i$ is the currect velocity
\overrightarrow{v_i}

2024-03-19 09:25 UTC, chraibi commented on content/models/social_force_model/index.md
> +## Agent force
## Repulsive force
(use same terminology as in the paper)

2024-03-19 09:25 UTC, chraibi commented on content/models/social_force_model/index.md
> +{{< figure src="Driving_Force.png" width="500">}}
Add captions to all figures. See other articles for example.

2024-03-19 09:25 UTC, chraibi commented on content/models/social_force_model/index.md
> +The agents exert a repulsive force on each other, which increases exponentially with their proximity. When they collide the pushing forces are increased additionally. When colliding, a frictional for
Agents exert an exponentially increasing repulsive force on each other as their proximity decreases. Upon collision, not only do the pushing forces intensify further, but a frictional force also arises. This frictional force acts perpendicularly to the repulsive force, aligning with the direction of the difference in speed.

2024-03-19 09:25 UTC, chraibi commented on content/models/social_force_model/index.md
> +$$\overrightarrow{f_{ij}} = [A_i exp[(r_{ij} - d_{ij})/B_i] + kg(r_{ij} - d_{ij})] \overrightarrow{n_{ij}} + \kappa g(r_{ij} - d_{ij}) \Delta v\_{ji}^t \overrightarrow{t_{ij}}$$
Use \exp instead of exp.

Equation is part of the text. So add some punctuation. In this case, a dot.

2024-03-19 09:25 UTC, chraibi commented on content/models/social_force_model/index.md
> +$$ \overrightarrow{F\_i^{\mathrm{ped}}} = \sum_{j} \overrightarrow{f_{ij}}$$
use "rep" for repulsive

2024-03-19 09:25 UTC, chraibi commented on content/models/social_force_model/index.md
> +* $d_{ij}$ is the distance between $i$ an $j$ them.
"is the distance between $i$ and $j$."

2024-03-19 09:25 UTC, chraibi commented on content/models/social_force_model/index.md
> +* $A_i$, $B_i$, $k$ and $\kappa$ are constants
are constants. 
remove the items and make reference to the table below.

2024-03-19 09:25 UTC, chraibi commented on content/models/social_force_model/index.md
> +* $g$ is a function with $g(x) =  \begin{cases}
$g$ represents the distance between pedestrians when they are in contact, and is zero when there is no contact.

2024-03-19 09:25 UTC, chraibi commented on content/models/social_force_model/index.md
> +{{< figure src="Pushing_Agents.png" caption="Direction of repulsive forces acting on an agent" width="500">}}
dot after agent

2024-03-19 09:25 UTC, chraibi commented on content/models/social_force_model/index.md
> +{{< figure src="Sliding_Agent_Forces.png" caption="Direction of the pushing and frictional forces acting on colliding agents">}}
dot after agents

2024-03-19 09:25 UTC, chraibi commented on content/models/social_force_model/index.md
> +The repulsive force is increases exponentially with decreasing distance. When the Obstacle collides with the agent the pushing forces are increased additionally. When colliding, a frictional force al
Obstacle -> obstacle

Actually, the agent collides with the obstacle not the other way around

2024-03-19 09:25 UTC, chraibi commented on content/models/social_force_model/index.md
> +* $ \overrightarrow{n_{ij}} = (n\_{ij}^1, n\_{ij}^2) = (\overrightarrow{pos\_i} - \overrightarrow{pos\_j})/d\_{ij} $ is the normalised vector from $j$ to $i$
pos should not be cursive.

2024-03-19 09:25 UTC, chraibi commented on content/models/social_force_model/index.md
> +* $\overrightarrow{n_{iW}} = (n\_{iW}^1, n\_{iW}^2) = (\overrightarrow{pos\_i} - \overrightarrow{pos\_W})/d\_{iW}$ the direction from $\overrightarrow{pos\_W}$ the closest point on the wall  to $i$
pos not cursive.

2024-03-19 09:25 UTC, chraibi commented on content/models/social_force_model/index.md
> +## Obstacle force
Consistency: You write about obstacles but right equations for walls.

2024-03-19 09:25 UTC, chraibi commented on content/models/social_force_model/index.md
> +{{< figure src="Pushing_Obstacle_Force.png" caption="Direction of repulsive forces acting on an agent" width="650">}}
dot

2024-03-19 09:25 UTC, chraibi commented on content/models/social_force_model/index.md
> +If the minimal distance to a wallsegment is smaller than the radius of an agent an additional frictional force occurs. This frictional force acts orthogonally to the repulsive force in the direction
When the minimum distance between an agent and a wall segment falls below the agent's radius, an additional frictional force comes into effect.

2024-03-19 09:25 UTC, chraibi commented on content/models/social_force_model/index.md
> +$$ \overrightarrow{v\_{new}} = \overrightarrow{v\_i} + [\overrightarrow{F\_i^{\mathrm{drv}}} + \frac{\overrightarrow{F\_i^{\mathrm{ped}}} + \overrightarrow{F\_i^{\mathrm{obst}}}}{m\_i}] \cdot \delta
obs or wall?
Maybe use "O" for obstacle and mention that obstacles are made of lines, then your figures still make sense.

2024-03-19 09:25 UTC, chraibi commented on content/models/social_force_model/index.md
> +$$ \overrightarrow{v\_{new}} = \overrightarrow{v\_i} + [\overrightarrow{F\_i^{\mathrm{drv}}} + \frac{\overrightarrow{F\_i^{\mathrm{ped}}} + \overrightarrow{F\_i^{\mathrm{obst}}}}{m\_i}] \cdot \delta
new and pos are not variables, so should not be cursive

2024-03-19 09:25 UTC, chraibi commented on content/models/social_force_model/index.md
> +$$ \overrightarrow{v\_{new}} = \overrightarrow{v\_i} + [\overrightarrow{F\_i^{\mathrm{drv}}} + \frac{\overrightarrow{F\_i^{\mathrm{ped}}} + \overrightarrow{F\_i^{\mathrm{obst}}}}{m\_i}] \cdot \delta
Equations need punctuation as well.

2024-03-25 12:48 UTC, ChristianHirt commented
Please check again whether the punctuation in equations has been done correctly.
Please let me know if the picture describing the driving force is understandable.

2024-03-26 12:56 UTC, chraibi commented on content/models/social_force_model/Driving_Force.png
The directions are ok, but not necessarily the norm of the vectors.

2024-03-28 04:52 UTC, chraibi approved these changes

2024-03-28 04:53 UTC, merged